# Generated by Django 5.2.8 on 2025-11-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('closest_big_city', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'airport',
                'ordering': ['name'],
            },
        ),
    ]
